services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10l"
      KVM: "N"          # Codesandbox: no /dev/kvm → force software emulation
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - windows_data:/storage
    restart: unless-stopped
    stop_grace_period: 2m

volumes:
  windows_data:


