services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10l"
      KVM: "N"
      DISK_SIZE: "15G"     # <-- limit the virtual disk to 15 GB
      DISK_FMT: "qcow2"    # optional, sparse format (doesn't preallocate)
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - windows_data:/storage
    restart: unless-stopped
    stop_grace_period: 2m

volumes:
  windows_data:
