services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/windows-10-tiny-b-4-x-64/Windows%2010%20%28Tiny%29.iso"
      KVM: "N"
      VNCPASS: "beboy123"
      RAM_SIZE: "6G"
      CPU_CORES: "6"
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - windows_data:/storage
    restart: unless-stopped
    stop_grace_period: 2m

volumes:
  windows_data: {}






