version: "3.9"

networks:
  appnet: {}

services:
  windows:
    image: dockurr/windows
    container_name: windows
    ports:
      - "3389:3389"
    environment:
      VERSION: "10l"
      KVM: "N"
      VNCPASS: "beboy123"
      RAM_SIZE: "8G"
      CPU_CORES: "6"
      DISK_SIZE: "14G"
      # These two lines force pre-allocation on the host disk
      DISK_FMT: "raw"
      DISK_PREALLOC: "Y"
      USERNAME: "BeboyRDP"
      PASSWORD: "beboy123"
    volumes:
      - windows_data:/storage
    restart: unless-stopped
    stop_grace_period: 2m
    networks: [appnet]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit
    environment:
      SECRET_KEY: "${secretkey}"
    network_mode: "service:windows"
    depends_on:
      - windows
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  # This now defines a standard, persistent volume on the disk
  windows_data: {}
