services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "10l"
      KVM: "N"
      DISK_SIZE: "8G" # Codesandbox: no /dev/kvm → force software emulation
    ports:
      - "8006:8006"
      - "3389:3389/tcp"
      - "3389:3389/udp"
    volumes:
      - type: tmpfs
        target: /storage
        tmpfs:
          size: 8g      # limit RAM usage to 8 GB
    restart: unless-stopped
    stop_grace_period: 2m


