version: "3.9"

networks:
  appnet: {}

services:
  windows:
    image: dockurr/windows
    container_name: windows
    ports:
      - "3389:3389"           
    environment:
      VERSION: "10l"
      KVM: "N"
      VNCPASS: "beboy123"
      RAM_SIZE: "6G"          # Guest RAM
      CPU_CORES: "6"          # Guest vCPUs
      DISK_SIZE: "8G"         # Matches tmpfs size
    volumes:
      - windows_data:/storage
    restart: unless-stopped
    stop_grace_period: 2m
    networks: [appnet]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit
    environment:
      SECRET_KEY: ""
    depends_on:
      - windows
    restart: unless-stopped
    networks: [appnet]
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "1"

volumes:
  windows_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=8g,uid=0,gid=0,mode=0755
