version: "3.9"

networks:
  appnet: {}

services:
  windows:
    image: dockurr/windows
    container_name: windows
    ports:
      - "3389:3389"
    environment:
      VERSION: "10l"
      KVM: "N"
      VNCPASS: "beboy123"
      RAM_SIZE: "12G"
      CPU_CORES: "6"
    volumes:
      - windows_data:/storage
    restart: unless-stopped
    stop_grace_period: 2m
    networks:
      - appnet

  playit:
    image: ghcr.io/playit-cloud/playit-agent:latest
    container_name: playit
    environment:
      SECRET_KEY: ""
    depends_on:
      - windows
    restart: unless-stopped
    networks:
      - appnet

volumes:
  windows_data: {}
